const imageCaptions = {
  "images/BAND RIDERS/RIDERS - AL GREEN.jpg": "AL GREEN - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - AXL ROSE.jpg": "AXL ROSE - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - BEYONCE.jpg": "BEYONCE - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - BILLY IDOL.jpg": "BILLY IDEOL - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - BRITTANY SPEARS.jpg": "BRITTANY SPEARS - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - BUSTA RHYMES.jpg": "BUSTA RHYMES - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - FOO FIGHTERS.jpg": "FOO FIGHTERS - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - FRANK SINATRA.jpg": "FRANK SINATRA - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - GAGA.jpg": "LADY GAGA - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - MARIAH CAREY.jpg": "MARIAH CAREY - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - MARILYN MANSON.jpg": "MARILYN MANSON - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - NEW KIDS.jpg": "NEW KIDS ON THE BLOCK - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - NINE INCH NAILS.jpg": "NINE INCH NAILS - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - PRINCE.jpg": "PRINCE - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - RIHANNA.jpg": "RIHANNA - 24x16in edition of 20, $1500",
  "images/BAND RIDERS/RIDERS - VAN HALEN.jpg": "VAN HALEN",
  "images/CANDY GOLDSWORTHY/HCH_3426-retouched.jpg": "Ice cream",
  "images/CANDY GOLDSWORTHY/HCH_3482-retouched.jpg": "Plastic fantastic",
  "images/CANDY GOLDSWORTHY/HCH_3549-retouched.jpg": "A black hole",
  "images/CANDY GOLDSWORTHY/HCH_3598- retouched.jpg": "",
  "images/CANDY GOLDSWORTHY/HCH_8001.jpg": "Sprinkle hydrant.",
  "images/CANDY GOLDSWORTHY/HCH_8067.jpg": "Swirl",
  "images/CANDY GOLDSWORTHY/HCH_8145.jpg": "Pizza ball",
  "images/DAMIENS DOTS/_MG_4886.jpg": "",
  "images/DAMIENS DOTS/_MG_4895.jpg": "",
  "images/DAMIENS DOTS/_MG_4921.jpg": "",
  "images/DAMIENS DOTS/_MG_4926.jpg": "",
  "images/DAMIENS DOTS/_MG_4926_large.jpg": "",
  "images/DAMIENS DOTS/_MG_4931.jpg": "",
  "images/FALLOUT OF THE FOOD SYSTEM/MUSHROOM CLOUD_01_25117F.jpg": "",
  "images/FALLOUT OF THE FOOD SYSTEM/MUSHROOM CLOUD_02_29908F.jpg": "",
  "images/FALLOUT OF THE FOOD SYSTEM/MUSHROOM CLOUD_02_30469F.jpg": "",
  "images/FALLOUT OF THE FOOD SYSTEM/MUSHROOM CLOUD_02_34328F.jpg": "",
  "images/FALLOUT OF THE FOOD SYSTEM/MUSHROOM CLOUD_02_37227F.jpg": "",
  "images/FOOD SCANS/1 Jan.jpg": "January",
  "images/FOOD SCANS/10 oct.jpg": "October",
  "images/FOOD SCANS/11 nov.jpg": "November",
  "images/FOOD SCANS/12 December B.jpg": "December",
  "images/FOOD SCANS/2 feb A.jpg": "February.",
  "images/FOOD SCANS/3 March.jpg": "March",
  "images/FOOD SCANS/4 April.jpg": "April",
  "images/FOOD SCANS/5 May.jpg": "May",
  "images/FOOD SCANS/6 June.jpg": "June",
  "images/FOOD SCANS/7 July.jpg": "July.",
  "images/FOOD SCANS/8 August.jpg": "August",
  "images/FOOD SCANS/9 September.jpg": "September",
  "images/FORTUNES OF A NATION/01-FORTUNE COOKIES31439.jpg": "Anti-Viagra",
  "images/FORTUNES OF A NATION/04-FORTUNE COOKIES14484 1.jpg": "Fake news.",
  "images/FORTUNES OF A NATION/07-FORTUNE COOKIES14461 1.jpg": "I'm a supermodel.",
  "images/FORTUNES OF A NATION/10-FORTUNE COOKIES14432 1.jpg": "Immaculate air.",
  "images/FORTUNES OF A NATION/13-FORTUNE COOKIES31464.jpg": "Huge financials.",
  "images/FORTUNES OF A NATION/16-FORTUNE COOKIES14040 1.jpg": "The only difference",
  "images/FORTUNES OF A NATION/18-FORTUNE COOKIES31398.jpg": "Shaking hands.",
  "images/FORTUNES OF A NATION/20-FORTUNE COOKIES14019 1.jpg": "Rich.",
  "images/FORTUNES OF A NATION/22-FORTUNE COOKIES31412.jpg": "Don't write good.",
  "images/FORTUNES OF A NATION/26-FORTUNE COOKIES31420.jpg": "Long and beautiful.",
  "images/FORTUNES OF A NATION/29-FORTUNE COOKIES14443 1.jpg": "Words",
  "images/FORTUNES OF A NATION/32-FORTUNE COOKIES14471 1.jpg": "I.Q.",
  "images/FORTUNES OF A NATION/37-FORTUNE COOKIES14491 1.jpg": "Temperament.",
  "images/GINGERBREAD ART GALLERIES/Guggenheim.jpg": "The Guggenheim",
  "images/GINGERBREAD ART GALLERIES/Karuizawa.jpg": "Karuizawa",
  "images/GINGERBREAD ART GALLERIES/Louvre.jpg": "The Louvre",
  "images/GINGERBREAD ART GALLERIES/MAS.jpg": "MAS",
  "images/GINGERBREAD ART GALLERIES/MAXXI.jpg": "MAXXI",
  "images/GINGERBREAD ART GALLERIES/Soumaya.jpg": "Soumaya",
  "images/GINGERBREAD ART GALLERIES/Tate Modern.jpg": "Tate Modern.",
  "images/HEMINGWAY LOOK-A-LIKES/DENIS GOLDEN_0025 1.jpg": "Dennis Golden",
  "images/HEMINGWAY LOOK-A-LIKES/DUSTY RHODES_1289 1.jpg": "Dusty Rhodes.",
  "images/HEMINGWAY LOOK-A-LIKES/FRED JOHNSON_1382 1.jpg": "Fred Johnson",
  "images/HEMINGWAY LOOK-A-LIKES/HARDY GOOD_1748 1.jpg": "Howdy Good.",
  "images/HEMINGWAY LOOK-A-LIKES/JOHN DAVIDSON_1479 1.jpg": "John Davidson",
  "images/HEMINGWAY LOOK-A-LIKES/MICHAEL GROOVER_1795 1.jpg": "Michael Groover",
  "images/HEMINGWAY LOOK-A-LIKES/RICHARD FILIP_1409 1.jpg": "Richard Filip",
  "images/HEMINGWAY LOOK-A-LIKES/ROBERT ORLIN_1824 1.jpg": "Robert Orlin",
  "images/HEMINGWAY LOOK-A-LIKES/STEPHEN TERRY_1707.jpg": "Stephen Terry",
  "images/HEMINGWAY LOOK-A-LIKES/WALT COLLINS_1834 1.jpg": "Walt Collins",
  "images/MRE TO MICHELIN/CHINA DESSERT.jpg": "",
  "images/MRE TO MICHELIN/CHINA MAIN copy.jpg": "",
  "images/MRE TO MICHELIN/CHINA_BAG.jpg": "",
  "images/MRE TO MICHELIN/FRANCE DESSERT copy.jpg": "",
  "images/MRE TO MICHELIN/FRANCE MAIN.jpg": "",
  "images/MRE TO MICHELIN/FRANCE_BAG.jpg": "",
  "images/MRE TO MICHELIN/RUSSIA DESSERT copy.jpg": "",
  "images/MRE TO MICHELIN/RUSSIA MAIN copy.jpg": "",
  "images/MRE TO MICHELIN/RUSSIA_BAG.jpg": "",
  "images/MRE TO MICHELIN/USA DESSERT copy.jpg": "",
  "images/MRE TO MICHELIN/USA MAIN copy.jpg": "",
  "images/MRE TO MICHELIN/USA_BAG.jpg": "",
  "images/NO SECONDS/Untitled-1.jpg": "",
  "images/NO SECONDS/Untitled-10.jpg": "",
  "images/NO SECONDS/Untitled-11.jpg": "",
  "images/NO SECONDS/Untitled-12.jpg": "",
  "images/NO SECONDS/Untitled-2.jpg": "",
  "images/NO SECONDS/Untitled-3.jpg": "",
  "images/NO SECONDS/Untitled-4.jpg": "",
  "images/NO SECONDS/Untitled-5.jpg": "",
  "images/NO SECONDS/Untitled-6.jpg": "",
  "images/NO SECONDS/Untitled-7.jpg": "",
  "images/NO SECONDS/Untitled-8.jpg": "",
  "images/NO SECONDS/Untitled-9.jpg": "",
  "images/POWER HUNGRY/EGYPT - H.jpg": "Egypt Have",
  "images/POWER HUNGRY/EGYPT - HN.jpg": "Egypt Have Not",
  "images/POWER HUNGRY/FRANCE - H.jpg": "France Have",
  "images/POWER HUNGRY/FRANCE - HN.jpg": "France Have Not.",
  "images/POWER HUNGRY/NORTH KOREA - H.jpg": "North Korea Have",
  "images/POWER HUNGRY/NORTH KOREA - HN.jpg": "North Korea Have Not",
  "images/POWER HUNGRY/ROME - H.jpg": "Rome Have",
  "images/POWER HUNGRY/ROME - HN.jpg": "Rome Have Not.",
  "images/POWER HUNGRY/SYRIA - HN.jpg": "Syria Have Not.",
  "images/POWER HUNGRY/SYRIA -H.jpg": "Surya Have",
  "images/POWER HUNGRY/USA - H.jpg": "USA Have",
  "images/POWER HUNGRY/USA - HN.jpg": "USA Have Not.",
  "images/RICE-KO/Burger.jpg": "The burger.",
  "images/RICE-KO/Cotton Candy with Candle.jpg": "Cotton candy with a candle.",
  "images/RICE-KO/Duck.jpg": "Duck",
  "images/RICE-KO/Martini.jpg": "Martini",
  "images/RICE-KO/Pool Room.jpg": "Pool room.",
  "images/RICE-KO/Sole.jpg": "Sole",
  "images/RICE-KO/Souffle.jpg": "Soufflé",
  "images/TOE JAM/BEEF_5642.jpg": "Feet and beef.",
  "images/TOE JAM/CAVIAR_5471.jpg": "Feet and caviar",
  "images/TOE JAM/CLAMS_5388.jpg": "Feet and clams.",
  "images/TOE JAM/EGGS_5214.jpg": "Feet and eggs.",
  "images/TOE JAM/FRUIT LOOPS_5322.jpg": "Feet and Fruit Loops",
  "images/TOE JAM/ICE CREAM_5518.jpg": "Feet and ice cream."
};
